language: node_js
node_js:
  - "7.7.3"

env:
  global:
    // COVERALLS_REPO_TOKEN
    secure: "lGV11CLOvR8aoWvmCKhcQ2q4VV6kL9nsEL+j19XP8Pt+bZnc0zmlRGUNcuS4eY28keepUswN2+Qsj2vQFAjgAl3v9NqJsCUL9Cl7dAzaZFlP1bFnTWMWBbBhdCQDuM6G7EQ5GB6I/g9/d7W6Ho4dPaf2enspghnigQfZRYoYhJepTmMycodft4COQ7TiGdrLNovEJzDLC5dCMLkMUt8C031GmWxX+s3KrnfmkSYKOBjxAe3tV2CDlMoYUo1OEL6W+bNcJhO8lePOCNVJYdU2Od+usSWirLEXLfs7yJPFjQjhwYZ9VbtaXTp7fZrZnJz7+Gcs+RdDOouNAxewzfLBYicpsAc2ht9TIaha0DX+9Afh6sIuRfVKEuAhNqrZdBlMwq/ttNDY7YsHNEvqzmsVD78XoQXM/QEcs1BasSNqntIbi/82RWn6ksfgu+eDqo7JNRyqjE9jNARSJeW7cz4NtRpDWZaoXezQHgBfW3rnJtbsipJisJrF60kyNw94sUmNckQaD91ieY6JI6Gj5Uiks0B7oTyGULkHewdEBcMfBEX38tlEfDt7/zdAjDEunV579YIhZy85FCgw8LOWTWUDS0dVAYgvEFn9iLz8UrCPYr9YzWvl7wERr/F4/6nF58XajFX4yNP02Fg1rR+Awh9DXLsN3NcxFbSCjEYwG/TDOZg="

cache:
  yarn: true

script:
  - npm run test:coverage
